import {
    BaseDTO,
    InsuredDTO,
    CoverageDTO,
    BenefitDTO,
    BenefitPartyDTO,
    FundAllocationDTO,
    ImpairmentRestrictionDTO,
    OwnerDTO,
    PayorDTO,
    ReviewMessageDTO,
    AddressDTO,
    PhoneDTO,
    RequirementDTO,
    AgencyDTO,
    AgentDTO,
    NoteDTO,
    ApplicationInfoDTO,
    TobaccoUseDTO,
    AmendmentDTO,
    ReinsurerDTO,
    MedicationDTO,
    WorksheetRowDTO,
    MedicalConditionDTO,
    PartyRelationDTO,
    EmployerDTO,
    FamilyHistoryDTO,
    RelatedPolicyDTO,
    PolicyCoverageDTO,
    LabDTO,
    LabResultDTO,
    LabCommentDTO,
    MIBDTO,
    MIBCodeDTO,
    MIBCodingDTO,
    MVRDTO,
    MVRDetailDTO,
    ParamedicalDTO,
    BeneficiaryDTO,
    EvidenceStatusDTO,
    VelogicaDTO,
    VelogicaDetailDTO,
    UserDTO,
    RoleDTO,
    AuthorizationLimitDTO
} from '../dto/';

/**
 * Constants for model data collections, such as lazy-load collections.
 */
export const DataCollectionNames = {
    Addresses: 'Addresses',
    AdminSystemMessages: 'AdminSystemMessages',
    Agencies: 'Agencies',
    Agents: 'Agents',
    Applications: 'Applications',
    Amendments: 'Amendments',
    AuthorizationLimits: 'AuthorizationLimits',
    Benefits: 'Benefits',
    BenefitParties: 'BenefitParties',
    Beneficiaries: 'Beneficiaries',
    FundAllocations: 'FundAllocations',
    Coverages: 'Coverages',
    Comments: 'Comments',
    EvidenceStatuses: 'EvidenceStatuses',
    Insureds: 'Insureds',
    ImpairmentRestrictions: 'ImpairmentRestrictions',
    Labs: 'Labs',
    LogEntries: 'LogEntries',
    MIBs: 'MIBs',
    Codes: 'Codes',
    MIBCoding: 'MibCodings',
    MVRs: 'MVRs',
    MedicalConditions: 'MedicalConditions',
    Medication: 'Medication',
    Notes: 'Notes',
    Owners: 'Owners',
    Parameds: 'Parameds',
    Payors: 'Payors',
    Phones: 'Phones',
    PolicyAdminStatuses: 'PolicyAdminStatuses',
    PrescriptionDrugs: 'PrescriptionDrugs',
    RelatedPolicies: 'RelatedPolicies',
    Relations: 'Relations',
    Requirements: 'Requirements',
    Results: 'Results',
    RetroInfos: 'RetroInfos',
    ReviewMessages: 'ReviewMessages',
    Roles: 'Roles',
    SystemSearches: 'SystemSearches',
    TeleApps: 'TeleApps',
    TobaccoUses: 'TobaccoUses',
    Velogicas: 'Velogicas',
    VelogicaDetails: 'Details',
    Reinsurers: 'Reinsurers',
    Employers: 'Employers',
    WorksheetRows: 'WorksheetRows',
    FamilyHistories: 'FamilyHistories',
    PolicyCoverages: 'PolicyCoverages',
    MVRDetails: 'Details',
    Users: 'Users'
};

export const DataCollectionNameToDTOMap: { readonly [dataType: string]: typeof BaseDTO } = {
    [DataCollectionNames.Insureds]: InsuredDTO,
    [DataCollectionNames.Coverages]: CoverageDTO,
    [DataCollectionNames.Benefits]: BenefitDTO,
    [DataCollectionNames.BenefitParties]: BenefitPartyDTO,
    [DataCollectionNames.Beneficiaries]: BeneficiaryDTO,
    [DataCollectionNames.FundAllocations]: FundAllocationDTO,
    [DataCollectionNames.ImpairmentRestrictions]: ImpairmentRestrictionDTO,
    [DataCollectionNames.Owners]: OwnerDTO,
    [DataCollectionNames.Payors]: PayorDTO,
    [DataCollectionNames.ReviewMessages]: ReviewMessageDTO,
    [DataCollectionNames.Addresses]: AddressDTO,
    [DataCollectionNames.Phones]: PhoneDTO,
    [DataCollectionNames.Requirements]: RequirementDTO,
    [DataCollectionNames.Agencies]: AgencyDTO,
    [DataCollectionNames.Agents]: AgentDTO,
    [DataCollectionNames.Notes]: NoteDTO,
    [DataCollectionNames.Applications]: ApplicationInfoDTO,
    [DataCollectionNames.TobaccoUses]: TobaccoUseDTO,
    [DataCollectionNames.Amendments]: AmendmentDTO,
    [DataCollectionNames.Reinsurers]: ReinsurerDTO,
    [DataCollectionNames.Employers]: EmployerDTO,
    [DataCollectionNames.WorksheetRows]: WorksheetRowDTO,
    [DataCollectionNames.Medication]: MedicationDTO,
    [DataCollectionNames.MedicalConditions]: MedicalConditionDTO,
    [DataCollectionNames.Relations]: PartyRelationDTO,
    [DataCollectionNames.FamilyHistories]: FamilyHistoryDTO,
    [DataCollectionNames.RelatedPolicies]: RelatedPolicyDTO,
    [DataCollectionNames.PolicyCoverages]: PolicyCoverageDTO,
    [DataCollectionNames.Labs]: LabDTO,
    [DataCollectionNames.Comments]: LabCommentDTO,
    [DataCollectionNames.Results]: LabResultDTO,
    [DataCollectionNames.MIBs]: MIBDTO,
    [DataCollectionNames.Codes]: MIBCodeDTO,
    [DataCollectionNames.MIBCoding]: MIBCodingDTO,
    [DataCollectionNames.MVRs]: MVRDTO,
    [DataCollectionNames.MVRDetails]: MVRDetailDTO,
    [DataCollectionNames.Parameds]: ParamedicalDTO,
    [DataCollectionNames.EvidenceStatuses]: EvidenceStatusDTO,
    [DataCollectionNames.Velogicas]: VelogicaDTO,
    [DataCollectionNames.VelogicaDetails]: VelogicaDetailDTO,
    [DataCollectionNames.Users]: UserDTO,
    [DataCollectionNames.AuthorizationLimits]: AuthorizationLimitDTO,
    [DataCollectionNames.Roles]: RoleDTO
};
