import { DBDate } from 'ls-core/model/util';
import { BaseModel } from 'ls-core/model/core';

export class PolicyByProductProxy extends BaseModel {
    public readonly $type: string = 'vpi.aus.insurance.core.PolicyByProductProxy, LifeSuite';

    public db_Name: string;
    public CompanyCode: string;
    public PolicyId: Object;
    public PolicyNumber: string;
    public Priority: Object;
    public PolicyStatusCode: string;
    public PolicyStatusDate: DBDate;
    public PolicyPersonId: Object;
    public InsuredTitle: string;
    public InsuredLastName: string;
    public InsuredMiddleName: string;
    public InsuredFirstName: string;
    public InsuredSuffix: string;
    public InsuredTaxId: string;
    public InsuredBirthDate: DBDate;
    public InsuredClientId: string;
    public InsuredUnderwritingAmount: Object;
    public ApplicationDate: DBDate;
    public ApplicationNumber: string;
    public AddedDate: DBDate;
    public ReceiveDate: DBDate;
    public ReopenDate: DBDate;
    public LastUnderwriteDate: DBDate;
    public UnderwriterId: Object;
    public UnderwriterLoginId: string;
    public TeamId: Object;
    public UserId: Object;
    public RequestedIssueDate: DBDate;
    public FinalActionDate: DBDate;
    public PartyId: Object;
    public CaseGroupId: string;
    public ServiceAssociateId: Object;
    public ServiceAssociateLoginId: string;
    public AssociationCode: string;
    public ApplicantStatusShort: string;
    public ApplicantStatusDate: DBDate;
    public IsMember: Object;
    public AdverseHistory: Object;
    public TpaCode: string;
    public PlanCodeId: string;
    public GNumber: string;
    public RelationshipToInsured: string;
    public CedentPolicyNumber: string;
    public CedentCompanyCode: string;
    public CedentUnderwriterId: Object;
    public CedentContactId: Object;
    public CedentDateSent: DBDate;
    public InternationalOrDomestic: string;
    public IdbFlag: string;
    public CurrencyCode: string;
    public EmployerId: Object;
    public AlternateCaseId: string;
    public SourceInfo: string;
    public DistributorCode: string;
    public AgentNumber: string;
    public AgencyNumber: string;
    public ApplicationSourceType: string;
    public MarketingCode: string;
    public CountryId: string;
    public CountryStateId: string;
    // public StateName: string;
    // public CountryName: string;
}
